version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/attendance"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
